<a href="https://colab.research.google.com/github/sejallotliker/Deep_learning_udemy_course/blob/Tensorflow_basics/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.12.0'

In [ ]:
#To create a Tensor (rank 0 tensor--> scalar)
a=tf.constant(3)
print(a)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
#rank 1 Tensor
b=tf.constant([1, 2, 3, 4])
print(b)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
#Rank 2 Tensor
c=tf.constant([[1,2], [3,4]]) #Matrix type tensor
print(c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#Converting a numpy array to a Tensor
array= np.array([1,2,3,4])
print("Before", array)
array=tf.convert_to_tensor(array)
print("After", array)

Before [1 2 3 4]
After tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


Arithmetic operations on Tensor

In [ ]:
#Sample 2D tensor
tensor=tf.constant([[1,2], [3,4]])


In [ ]:
#Add 1 to all positions
tensor=tf.add(tensor,1)
print("added 1", tensor)

added_1 tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
#subtract 1 from all positions
tensor=tf.subtract(tensor,1)
print("subtracted 1", tensor)

subtracted 1 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#multiply 2 from all positions
tensor=tf.multiply(tensor,2)
print("multiplied 2", tensor)

multiplied 1 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


In [ ]:
#divide 2 from all positions
tensor=tf.divide(tensor,2)
print("divide 2", tensor)

divide 2 tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


Matrix Multiplication

In [ ]:
tensor=tf.constant([[1,2], [3,4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor=tf.constant([[1,2], [3,4]])
tf.multiply(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

#Activation Functions in Neural Network

In [ ]:
#To build a neural network using activation functions
tensor=tf.constant([[1,2], [5, 10]], dtype=tf.float64)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [ ]:
#applying softmax
tf.nn.softmax(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.26894142, 0.73105858],
       [0.00669285, 0.99330715]])>

In [ ]:
#applying sigmoid
tf.nn.sigmoid(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.73105858, 0.88079708],
       [0.99330715, 0.9999546 ]])>

In [ ]:
#Applying relu
tf.nn.relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [ ]:
#Applying leaky relu
tf.nn.leaky_relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

#Optimizers

In [ ]:
optimizer=tf.keras.optimizers.Adam()
print(optimizer)

#Basic structure of a neural network

In [ ]:
#Start your model with sequential Object
model=tf.keras.models.Sequential()

#Next add in your input object and specify the dimension you want to pass in
model.add(tf.keras.Input(shape=(10,))) #no of columns

#Add in your Neurons of 1st layer
model.add(tf.keras.layers.Dense(32))

#2nd layer
model.add(tf.keras.layers.Dense(16))

#Print summary to understand your neural network flow
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 32)                352       
                                                                 
 dense_3 (Dense)             (None, 16)                528       
                                                                 
Total params: 880
Trainable params: 880
Non-trainable params: 0
_________________________________________________________________
